NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier: # Dont need this on Peer MSP (but for simplify, just keep it)
    Certificate: cacerts/localhost-7054-ca-org.pem
    OrganizationalUnitIdentifier: orderer